spring:
  datasource:
    driverClassName: org.postgresql.Driver
    password: admin
    url: jdbc:postgresql://localhost:5432/cartAPI?currentSchema=test
    username: postgres
  liquibase:
    change-log: classpath:db/db.changelog-master.yaml
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
