logging:
  file: .cartAPI.log
  level:
    root: INFO
server:
  port: 3000
spring:
  banner:
    location: classpath:banner.txt
  datasource:
    driverClassName: org.postgresql.Driver
    password: admin
    url: jdbc:postgresql://localhost:5432/cartAPI
    username: postgres
  liquibase:
    change-log: classpath:db/db.changelog-master.yaml
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
